name: Automatic Testing on Push

on:
   push:
      branches: "*"

jobs:
   testing:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v4

         # Add caching for dependencies
         - name: Cache node modules
           uses: actions/cache@v3
           with:
              path: node_modules
              key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-node-

         # Combine installations into one step to reduce overhead
         - name: Install dependencies
           run: |
              sudo apt-get update && sudo apt-get install -y libgbm-dev xvfb
              yarn install --frozen-lockfile
              yarn playwright install chromium --with-deps

         # Configure both Electron and start xvfb in one step
         - name: Setup test environment
           run: |
              sudo chown root:root node_modules/electron/dist/chrome-sandbox
              sudo chmod 4755 node_modules/electron/dist/chrome-sandbox
              Xvfb :99 -screen 0 1920x1080x16 &
           env:
              DISPLAY: ":99.0"

         - name: Run tests
           run: yarn test
           env:
              DISPLAY: ":99.0"

         # Only upload test results if tests generate them
         - name: Upload test results
           if: always()
           uses: actions/upload-artifact@v4
           with:
              name: test-results
              path: logs/results.json
              if-no-files-found: ignore
