name: Automatic Testing on Push

on:
   push:
      branches: "*"

jobs:
   testing:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Install dependencies
           run: |
              sudo apt-get update
              sudo apt-get install -y libgbm-dev xvfb
              yarn install
              yarn playwright install --with-deps

         - name: Configure Electron sandbox
           run: |
              sudo chown root:root node_modules/electron/dist/chrome-sandbox
              sudo chmod 4755 node_modules/electron/dist/chrome-sandbox

         - name: Set up xvfb
           run: |
              Xvfb :99 -screen 0 1920x1080x16 &
           env:
              DISPLAY: ":99.0"

         - name: Run tests
           run: yarn test
           env:
              DISPLAY: ":99.0"
              DEBUG: pw:browser*

         - name: Upload test results
           uses: actions/upload-artifact@v4
           with:
              name: test-results
              path: logs/results.json
