name: Automatic Testing on Push

on:
   push:
      branches: "*"

jobs:
   testing:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Install dependencies
           run: |
              sudo apt-get install -y libgbm-dev
              yarn install
              yarn playwright install --with-deps

         - name: Set up xvfb
           run: |
              sudo apt-get install xvfb
              export DISPLAY=':99.0'
              Xvfb :99 -screen 0 1920x1080x16 &

         - name: Run tests
           run: |
              yarn test
           env:
              DEBUG: pw:browser*

         - name: Upload test results
           uses: actions/upload-artifact@v4
           with:
              name: test-results
              path: logs/results.json
